### ISSUE TITLE
Verificando se a transação foi autorizada

### ISSUE THREAD

**Issue by sdsanches** [DeveloperCielo/Webservice-1.5-java-lojaexemplo#3]
Implementei em um cliente, e em fase de testes me deparei com o seguinte:
Na classe StatusTransacao, temos os códigos:

```
public static StatusTransacao valueOf(short codigo) {
		switch(codigo) {
			case 0: return CRIADA;
			case 1: return EM_ANDAMENTO; 
			case 2: return AUTENTICADA;
			case 3: return NAO_AUTENTICADA;
			case 4: return AUTORIZADA;
			case 5: return NAO_AUTORIZADA;
			case 6: return CAPTURADA;
			case 8: return NAO_CAPTURADA;
			case 9: return CANCELADA;
			case 10: return EM_AUTENTICACAO;
			default:
				throw new IllegalArgumentException("Status '" + codigo + "' não catalogado");
		}
}
```

Na  documentação da Cielo, existem duas tabelas de códigos, [Códigos de Autorização IR](https://developercielo.github.io/Webservice-1.5/#códigos-de-autorização-lr) e [Status das Transações](https://developercielo.github.io/Webservice-1.5/#status-das-transações)

Ao criar uma nova Transação, recebo o objeto Transacao como retorno, então para verificar o Status faço o seguinte:

```
if (transacao.getStatusTransacao().isAutorizada()) {
       // ...
}
```

No entanto, mesmo utilizando um cartão inválido, ela vem como autorizada no ambiente de testes.

Estou utilizando o SDK de forma incorreta? 
Há outra maneira de verificar se a transação foi aprovada ou não?

Fico aguardando, obrigado!

**Comment by netojoaobatista** [comment]
Por favor, utilize os dados de testes conforme descrito no manual, em [Testes e Homologação](https://developercielo.github.io/Webservice-1.5/#testes-e-homologação)
